Typescript test
monicagil/protractor-workshop-2017 pull request #3
Opened 2017-10-03 21:41 UTC by monicagil

2017-10-03 21:51 UTC, aperdomob requested changes

2017-10-03 21:51 UTC, aperdomob commented on package.json
> +    "test": "npm run build && protractor dist/protractor/config.js"
faltan algunos scripts

2017-10-03 21:51 UTC, aperdomob commented on package.json
> +}
Agregar salto de linea

2017-10-03 21:51 UTC, aperdomob commented on tsconfig.json
> +}
agregar salto de línea

2017-10-03 23:35 UTC, aperdomob commented on package.json
> +   "clean": "DEL dist",
trabaja en una consola linux, puede ser cygwin, cmder o la de github, ya que si ejecutamos esto en integración continua nos va a fallar

2017-10-04 13:13 UTC, jhenaoz requested changes
cambiar el script de clean

2017-10-04 16:14 UTC, aperdomob requested changes

2017-10-04 16:14 UTC, aperdomob commented on .gitignore
>  # End of https://www.gitignore.io/api/osx,node,visualstudiocode
agregar fin de linea

2017-10-04 16:32 UTC, aperdomob approved these changes

2017-10-04 18:37 UTC, jhenaoz approved these changes

2017-10-04 18:40 UTC, merged